/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOHARMONIC
#define ROOHARMONIC

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooHarmonic : public RooAbsPdf {
public:
  RooHarmonic() {} ; 
  RooHarmonic(const char *name, const char *title,
	      RooAbsReal& _cpsi,
	      RooAbsReal& _theta,
	      RooAbsReal& _phi,
	      RooAbsReal& _C);
  RooHarmonic(const RooHarmonic& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooHarmonic(*this,newname); }
  inline virtual ~RooHarmonic() { }

protected:

  RooRealProxy cpsi ;
  RooRealProxy theta ;
  RooRealProxy phi ;
  RooRealProxy C ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooHarmonic,1) // Your description goes here...
};
 
#endif
